### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by drpatelh** [nf-core/atacseq#236]
- [x] Check `--email` is working properly
- [x] Check channels to IGV and MultiQC and that reports look the same as with v1.2.2
- [x] Check published file paths match those in output docs
- [x] Check we have listed all issues in the CHANGELOG where we have provided a fix (not for questions or others where we suggest to try the new version of the pipeline)
- [x] Diff between modules used in chipseq to see differences 
- [x] Collect and add software version changes to CHANGELOG
- [x] Why is this used in pipeline: `PREPARE_GENOME.out.filtered_bed.first()?`
- [x] Check container versions are all the same in the pipeline to avoid pulling containers with the different version of tools
- [x]  (see [comment](https://github.com/nf-core/atacseq/issues/236#issuecomment-1326620043) below) Test pipeline with single sample in samplesheet
- [x] Check everything is working as expected when merging replicates for samples where no replicates exist
- [x] Add sample(s) to tests for single-end data
- [x] Test pipeline if `--blacklist false`

**Comment by JoseEspinosa** [comment]
For the `Test pipeline with single sample in samplesheet` the pipeline works but some processes are run both by the `merged_library` and by the `merged_replicate` with the same sample so I don't whether this was the intention seems it seems to be not very efficient, e.g.:
```
#!/bin/bash -euo pipefail
macs2 \
    callpeak \
    --keep-dup all --nomodel --broad --broad-cutoff 0.1 \
    --gsize 11624332 \
    --format BAMPE \
    --name OSMOTIC_STRESS_T0_REP1 \
    --treatment OSMOTIC_STRESS_T0_REP1.mLb.clN.sorted.bam \
...
```
vs.
```
#!/bin/bash -euo pipefail
macs2 \
    callpeak \
    --keep-dup all --nomodel --broad --broad-cutoff 0.1 \
    --gsize 11624332 \
    --format BAMPE \
    --name OSMOTIC_STRESS_T0 \
    --treatment OSMOTIC_STRESS_T0.mRp.mkD.sorted.bam \
...
```

**Comment by drpatelh** [comment]
Nope. We need to fix that. Thanks 👍🏽

**Comment by JoseEspinosa** [comment]
I close the issue since the version 2.0.0 of the pipeline has been released
